name: CI build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build Native Executable
        run: ./mvnw package -Dnative -DskipTests
      
      - name: Build Docker Image
        run: |
          docker build -f src/main/docker/Dockerfile.native-distroless \
          -t dev.thiagotoyomoto/quarkus-ci-cd-example .

      - name: Upload Native Binary
        uses: actions/upload-artifact@v4
        with:
          name: native-executable
          path: target/*-runner
          
        
        
